# Generated by Django 3.0.1 on 2019-12-27 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191227_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 2, 28, 35, 430279)),
        ),
        migrations.AlterField(
            model_name='game_info',
            name='date_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 2, 28, 35, 429312)),
        ),
    ]
