# Generated by Django 3.0.1 on 2019-12-27 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191227_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numb',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 3, 44, 56, 263626)),
        ),
        migrations.AlterField(
            model_name='game_info',
            name='date_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 3, 44, 56, 262571)),
        ),
    ]
