# Generated by Django 3.0.1 on 2019-12-27 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191227_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BetterVersion', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gen',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 6, 48, 53, 453711)),
        ),
        migrations.AlterField(
            model_name='game_info',
            name='date_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 6, 48, 53, 452625)),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Evolution'),
        ),
    ]
